version: "2"
services:
    web:
      build: 
        context: .
        args:
          COMPOSER_INSTALL:
          NPM_INSTALL:
      image: xachman/territory
      links:
        - mysql:mysqlhost
        - testdb:testhost
      environment:
        - VIRTUAL_HOST=territory.dev
      volumes: 
        - ./:/var/www/
        - /var/www/vendor
        - /var/www/node_modules
      ports:
        - "127.0.0.1:5660:80"
    mysql:
        image: mysql:5.7
        ports:
          - 3309:3306
        environment:
          MYSQL_DATABASE: territory
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    testdb:
      image: mysql
      environment:
        MYSQL_DATABASE: testdb
        MYSQL_ROOT_PASSWORD: root

