version: "2"
services:
    web:
      build: 
        context: .
        args:
          COMPOSER_INSTALL: --no-dev
          NPM_INSTALL: --production
      image: xachman/territory
      external_links:
        - mddd:mdddhost
      environment:
        - VIRTUAL_HOST=territory.dev
      ports:
        - "0:80"
      volumes: 
        - ./:/var/www/
        - /var/www/vendor
        - /var/www/node_modules
      network_mode: bridge

